HARDWARE:
  NUM_GPUS: 1
  NUM_WORKERS: 11
LOG:
  OUTPUT_PATH: ./output
  CHECKPOINT_FREQUENCY: 16000
  SUPERVISED_LOG: 4000
  SUPERVISED_VALIDATION: 4000
  UNSUPERVISED_LOG: 0
  UNSUPERVISED_VALIDATION: 0
DATASET:
  NAME: SNEMI3D
  SSL_CROP_SIZE: [22, 136, 136]
  PADDING: [20, 64, 64]
  DATA_ROOT: ./dataset
  MEAN: 145.801
  STD: 31.695
  BOUNDARY_EROSION: 1
  LABEL_SMOOTHING: 0
AUGMENTATION:
  CONTRAST_FACTOR: 0.3
  BRIGHTNESS_FACTOR: 0.3
  WARP_ALPHA: 16
  WARP_SIGMA: 4
  BLUR_SECTIONS: 4
  BLUR_KERNEL: 5
  CUT_RATIO: 0.25
  CUT_DOWNSAMPLE: 2.0
  MISSING_PARTS: 32
  MISSING_SECTIONS: 2
  MISALIGNMENT: 16
MODEL:
  INPUT_SIZE: [ 20, 128, 128 ]
  OUTPUT_SIZE: [ 20, 128, 128 ]
  FILTERS: [32, 64, 128, 256]
  STEM_KERNEL_SIZE: [ 1, 5, 5 ]
  STEM_STRIDE: [ 1, 1, 1 ]
  STEM_PADDING: [0, 2, 2]
  NORM: batch_norm
  PADDING: replicate
  BOUNDARY_HEAD: BoundaryHead
  EMBEDDING_HEAD: EmbeddingHead
  EMBEDDING_DIMENSION: 24
  ZERO_INIT_RESIDUALS: true
SSL:
  MODEL: SimSiam
  PROJECTION_HEAD: MLPProjectionHead
  PROJECTION_POOLING: [20, 16, 16]
  PROJECTION_DIMENSION: 256
OPTIM:
  OPTIMIZER: Adam
  SUPERVISED_STEPS: 120000
  UNSUPERVISED_STEPS: 0
  WEIGHT_DECAY: 0.0001
  LR_SCHEDULER_NAME: CosineAnnealingWarmRestarts
  INITIAL_LR: 0.003
  T_0: 8000
  T_MULT: 2
  TOTAL_ITER: 120000
  BATCH_SIZE: 8
LOSS:
  ALPHA: 1
  BETA: 1
  GAMMA: 1e-3
  DELTA: 1.5
  RECOMPUTE_CONNECTED_COMPONENTS: true
INFERENCE:
  BATCH_SIZE: 64
  THREADS: 4
  STRIDE: [8, 48, 48]
  BLENDING: bump
  INPUT_SIZE: [20, 128, 128]
  OUTPUT_CROP_SIZE: [16, 96, 96]
  MWS_STRIDE: [1, 1, 1]
  MWS_BACKGROUND: 0.6
  OFFSET_VECTORS: [[-1, 0, 0],
                   [0, -1, 0],
                   [0, 0, -1],
                   [-2,0,0],
                   [0,-5,0],
                   [0,0,-5],
                   [0,-5,-5],
                   [0,-5,5],
                   [-1,-5,0],
                   [-1,0,-5],
                   [1,-5,0],
                   [1,0,-5]]